apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: ebs-static 
spec:
  accessModes:
  - ReadWriteOnce 
  capacity:
    storage: 2Gi 
  csi:
    driver: ebs.csi.aws.com 
    fsType: ext4 
    volumeHandle: vol-0e7f64b5320c582a6

  